//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient1.SelfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Test1", Namespace="http://schemas.datacontract.org/2004/07/SelfHost")]
    [System.SerializableAttribute()]
    public partial class Test1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfServiceReference.ISelfService")]
    public interface ISelfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/get_CallsCount", ReplyAction="http://tempuri.org/ISelfService/get_CallsCountResponse")]
        int get_CallsCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/get_CallsCount", ReplyAction="http://tempuri.org/ISelfService/get_CallsCountResponse")]
        System.Threading.Tasks.Task<int> get_CallsCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/SetTestObject", ReplyAction="http://tempuri.org/ISelfService/SetTestObjectResponse")]
        string SetTestObject(WCFClient1.SelfServiceReference.Test1 testObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfService/SetTestObject", ReplyAction="http://tempuri.org/ISelfService/SetTestObjectResponse")]
        System.Threading.Tasks.Task<string> SetTestObjectAsync(WCFClient1.SelfServiceReference.Test1 testObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISelfServiceChannel : WCFClient1.SelfServiceReference.ISelfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelfServiceClient : System.ServiceModel.ClientBase<WCFClient1.SelfServiceReference.ISelfService>, WCFClient1.SelfServiceReference.ISelfService {
        
        public SelfServiceClient() {
        }
        
        public SelfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int get_CallsCount() {
            return base.Channel.get_CallsCount();
        }
        
        public System.Threading.Tasks.Task<int> get_CallsCountAsync() {
            return base.Channel.get_CallsCountAsync();
        }
        
        public string SetTestObject(WCFClient1.SelfServiceReference.Test1 testObject) {
            return base.Channel.SetTestObject(testObject);
        }
        
        public System.Threading.Tasks.Task<string> SetTestObjectAsync(WCFClient1.SelfServiceReference.Test1 testObject) {
            return base.Channel.SetTestObjectAsync(testObject);
        }
    }
}
